### ISSUE TITLE
remove osgi bundle header: Require-Capability: JavaSE-9

### ISSUE THREAD

**Issue by slandelle** [random-maven/scalor-maven-plugin#6]
Hi there,

I get the following stacktrace:

```
Execution failure: (com.carrotgarden.maven:scalor-maven-plugin_2.12:1.2.2.20180214213630:eclipse-config:default:initialize) 
 org.apache.maven.plugin.MojoFailureException: Execution failure: at com.carrotgarden.maven.scalor.base.Mojo.execute(Mojo.scala:57) 
 at com.carrotgarden.maven.scalor.base.Mojo.execute$(Mojo.scala:40) at 
 com.carrotgarden.maven.scalor.EclipseConfigMojo.execute(EclipseMojo.scala:106) at 
 org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
 org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360) at 
 org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200) at 
 org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:
 42) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246) at 
 org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:
 42) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304) at 
 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360) at 
 org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383) at 
 org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142) at 
 org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56) 
 Caused by: org.osgi.framework.BundleException: Could not resolve module: com.carrotgarden.maven.scalor-maven-
 plugin_2.12_1.2.2.20180214213630 [600] Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)
 (version=9.0))" at org.eclipse.osgi.container.Module.start(Module.java:444) at 
 org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) at 
 org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402) at 
 com.carrotgarden.maven.scalor.EclipseConfigMojo.performEclipse(EclipseMojo.scala:142) at 
 com.carrotgarden.maven.scalor.EclipseAnyMojo.perform(EclipseMojo.scala:93) at 
 com.carrotgarden.maven.scalor.EclipseAnyMojo.perform$(EclipseMojo.scala:84) at 
 com.carrotgarden.maven.scalor.EclipseConfigMojo.perform(EclipseMojo.scala:106) at 
 com.carrotgarden.maven.scalor.base.Mojo.execute(Mojo.scala:51) ... 34 more
```

I suspect this happens because I run eclipse with JDK8.
Even though I have Java 9 on my machine, I force eclipse to launch with Java 8 (set -vm option in eclipse.ini). I cannot launch with Java 9 because I've stumbled upon a bug in m2e and forcing Java 8 is the only work around I have so far.

Regards

**Comment by Andrei-Pozolotin** [comment]
ok, fixing

**Comment by slandelle** [comment]
Thanks!
BTW, would you know where to report an issue against m2e?

**Comment by Andrei-Pozolotin** [comment]
1. re: "Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)
 (version=9.0))""
please try Scalor v 1.2.3
https://bintray.com/random-maven/maven/scalor-maven-plugin_2.12

2. re: " I've stumbled upon a bug in m2e"
please try M2E v 1.9
https://repository.takari.io/content/sites/m2e.extras/m2e/1.9.0/N/LATEST/

3. re: "where to report an issue against m2e"
try here:
https://bugs.eclipse.org/bugs/enter_bug.cgi?product=m2e

**Comment by slandelle** [comment]
> re: "Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)
(version=9.0))""
please try Scalor v 1.2.3
https://bintray.com/random-maven/maven/scalor-maven-plugin_2.12

Fix confirmed, thanks a lot!!!

> re: " I've stumbled upon a bug in m2e"
please try M2E v 1.9
https://repository.takari.io/content/sites/m2e.extras/m2e/1.9.0/N/LATEST/

I already tried that and bug is still there.

> re: "where to report an issue against m2e"
try here:
https://bugs.eclipse.org/bugs/enter_bug.cgi?product=m2e

Will do, thanks!

**Comment by Andrei-Pozolotin** [comment]
released:
http://repo1.maven.org/maven2/com/carrotgarden/maven/scalor-maven-plugin_2.12/

**Comment by hellboy81** [comment]
I have `Require-Capability` with version `9.0`:

`Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9.0))"`

How can I detect problem dependency?

```java
Bundle-ClassPath: .,META-INF/lib/accessors-smart-1.2.jar,META-INF/lib/an
 imal-sniffer-annotations-1.17.jar,META-INF/lib/antlr4-runtime-4.7.1.jar
 ,META-INF/lib/asm-5.0.4.jar,META-INF/lib/checker-qual-2.5.2.jar,META-IN
 F/lib/commons-codec-1.9.jar,META-INF/lib/commons-lang3-3.7.jar,META-INF
 /lib/commons-logging-1.2.jar,META-INF/lib/error_prone_annotations-2.2.0
 .jar,META-INF/lib/failureaccess-1.0.1.jar,META-INF/lib/feign-annotation
 -error-decoder-1.2.0.jar,META-INF/lib/feign-core-10.2.3.jar,META-INF/li
 b/feign-form-3.8.0.jar,META-INF/lib/feign-jackson-10.2.3.jar,META-INF/l
 ib/feign-okhttp-10.2.3.jar,META-INF/lib/feign-slf4j-10.2.3.jar,META-INF
 /lib/guava-27.0.1-jre.jar,META-INF/lib/hamcrest-core-1.3.jar,META-INF/l
 ib/handlebars-4.0.7.jar,META-INF/lib/handlebars-helpers-4.0.7.jar,META-
 INF/lib/httpclient-4.5.5.jar,META-INF/lib/httpcore-4.4.9.jar,META-INF/l
 ib/j2objc-annotations-1.1.jar,META-INF/lib/jackson-annotations-2.9.8.ja
 r,META-INF/lib/jackson-core-2.9.8.jar,META-INF/lib/jackson-databind-2.9
 .8.jar,META-INF/lib/jackson-datatype-jdk8-2.9.8.jar,META-INF/lib/jackso
 n-datatype-jsr310-2.9.8.jar,META-INF/lib/jackson-datatype-threetenbp-2.
 8.4.jar,META-INF/lib/jackson-module-parameter-names-2.9.8.jar,META-INF/
 lib/jetty-continuation-9.2.24.v20180105.jar,META-INF/lib/jetty-http-9.2
 .24.v20180105.jar,META-INF/lib/jetty-io-9.2.24.v20180105.jar,META-INF/l
 ib/jetty-security-9.2.24.v20180105.jar,META-INF/lib/jetty-server-9.2.24
 .v20180105.jar,META-INF/lib/jetty-servlet-9.2.24.v20180105.jar,META-INF
 /lib/jetty-servlets-9.2.24.v20180105.jar,META-INF/lib/jetty-util-9.2.24
 .v20180105.jar,META-INF/lib/jetty-webapp-9.2.24.v20180105.jar,META-INF/
 lib/jetty-xml-9.2.24.v20180105.jar,META-INF/lib/jopt-simple-5.0.3.jar,M
 ETA-INF/lib/json-20140107.jar,META-INF/lib/json-path-2.4.0.jar,META-INF
 /lib/json-smart-2.3.jar,META-INF/lib/jsr305-3.0.2.jar,META-INF/lib/juni
 t-4.12.jar,META-INF/lib/listenablefuture-9999.0-empty-to-avoid-conflict
 -with-guava.jar,META-INF/lib/log4j-1.2.17.jar,META-INF/lib/log4j-api-2.
 11.2.jar,META-INF/lib/log4j-to-slf4j-2.11.2.jar,META-INF/lib/lombok-1.1
 8.8.jar,META-INF/lib/okhttp-3.6.0.jar,META-INF/lib/okio-1.11.0.jar,META
 -INF/lib/org.apache.oltu.oauth2.client-1.0.2.jar,META-INF/lib/org.apach
 e.oltu.oauth2.common-1.0.2.jar,META-INF/lib/slf4j-log4j12-1.7.26.jar,ME
 TA-INF/lib/swagger-annotations-2.0.7.jar,META-INF/lib/threetenbp-1.3.2.
 jar,META-INF/lib/wiremock-2.19.0.jar,META-INF/lib/xmlunit-core-2.5.1.ja
 r,META-INF/lib/xmlunit-legacy-2.5.1.jar,META-INF/lib/zjsonpatch-0.4.4.j
 ar
```

```java
Import-Package: 
 javax.ws.rs;version="[1,2)",
 javax.ws.rs.core;version="[1,2)",
 javax.servlet;version="3.1.0",
 javax.servlet.annotation;version="3.1.0",
 javax.servlet.descriptor;version="3.1.0",
 javax.servlet.http;version="3.1.0",
 javax.xml.bind;version="[2.1,3)",
 javax.xml.bind.annotation;version="[2.1,3)",
 javax.xml.bind.util;version="[2.1,3)",
 android.util;version=0;resolution:=optional,
 com.atlassian.jira.config;version=0;resolution:=optional,
 com.atlassian.jira.exception;version=0;resolution:=optional,
 com.atlassian.jira.issue;version=0;resolution:=optional,
 com.atlassian.jira.issue.fields;version=0;resolution:=optional,
 com.atlassian.jira.issue.fields.config;version=0;resolution:=optional,
 com.atlassian.jira.issue.fields.layout.field;version=0;resolution:=opti
 onal,
 com.atlassian.jira.issue.issuetype;version=0;resolution:=optional,
 com.atlassian.jira.issue.label;version=0;resolution:=optional,
 com.atlassian.jira.issue.util;version=0;resolution:=optional,
 com.atlassian.jira.permission;version=0;resolution:=optional,
 com.atlassian.jira.project;version=0;resolution:=optional,
 com.atlassian.jira.security;version=0;resolution:=optional,
 com.atlassian.jira.user;version=0;resolution:=optional,
 com.atlassian.plugin.spring.scanner.annotation.component;version=0;reso
 lution:=optional,
 com.atlassian.plugin.spring.scanner.annotation.imports;version=0;resolu
 tion:=optional,
 com.atlassian.plugins.rest.common.security;version=0;resolution:=option
 al,
 com.atlassian.sal.api.auth;version=0;resolution:=optional,
 com.atlassian.templaterenderer;version=0;resolution:=optional,
 com.google.gson;version=0;resolution:=optional,
 com.google.gson.reflect;version=0;resolution:=optional,
 com.ibm.uvm.tools;version=0;resolution:=optional,
 com.sun.jdmk.comm;version=0;resolution:=optional,
 com.sun.org.apache.xerces.internal.jaxp;version=0;resolution:=optional,
 com.sun.tools.javac.processing;version=0;resolution:=optional,
 com.sun.tools.javac.util;version=0;resolution:=optional,
 io.swagger.annotations;version=0;resolution:=optional,
 javax.annotation.processing;version=0;resolution:=optional,
 javax.crypto;version=0;resolution:=optional,
 javax.crypto.spec;version=0;resolution:=optional,
 javax.imageio;version=0;resolution:=optional,
 javax.jmdns;version=0;resolution:=optional,
 javax.jms;version=0;resolution:=optional,
 javax.lang.model;version=0;resolution:=optional,
 javax.lang.model.element;version=0;resolution:=optional,
 javax.lang.model.type;version=0;resolution:=optional,
 javax.mail;version=0;resolution:=optional,
 javax.mail.internet;version=0;resolution:=optional,
 javax.management;version=0;resolution:=optional,
 javax.naming;version=0;resolution:=optional,
 javax.naming.directory;version=0;resolution:=optional,
 javax.naming.ldap;version=0;resolution:=optional,
 javax.net;version=0;resolution:=optional,
 javax.net.ssl;version=0;resolution:=optional,
 javax.security.auth;version=0;resolution:=optional,
 javax.security.auth.x500;version=0;resolution:=optional,
 javax.sql;version=0;resolution:=optional,
 javax.swing;version=0;resolution:=optional,
 javax.swing.border;version=0;resolution:=optional,
 javax.swing.event;version=0;resolution:=optional,
 javax.swing.table;version=0;resolution:=optional,
 javax.swing.text;version=0;resolution:=optional,
 javax.swing.text.html;version=0;resolution:=optional,
 javax.swing.text.html.parser;version=0;resolution:=optional,
 javax.swing.tree;version=0;resolution:=optional,
 javax.tools;version=0;resolution:=optional,
 javax.validation.constraints;version=0;resolution:=optional,
 javax.xml.datatype;version=0;resolution:=optional,
 javax.xml.namespace;version=0;resolution:=optional,
 javax.xml.parsers;version=0;resolution:=optional,
 javax.xml.transform;version=0;resolution:=optional,
 javax.xml.transform.dom;version=0;resolution:=optional,
 javax.xml.transform.sax;version=0;resolution:=optional,
 javax.xml.transform.stream;version=0;resolution:=optional,
 javax.xml.validation;version=0;resolution:=optional,
 javax.xml.xpath;version=0;resolution:=optional,
 org.apache.avalon.framework.logger;version=0;resolution:=optional,
 org.apache.log;version=0;resolution:=optional,
 org.apache.tapestry5.json;version=0;resolution:=optional,
 org.apache.tools.ant;version=0;resolution:=optional,
 org.apache.tools.ant.types;version=0;resolution:=optional,
 org.codehaus.jettison.json;version=0;resolution:=optional,
 org.eclipse.core.resources;version=0;resolution:=optional,
 org.eclipse.core.runtime;version=0;resolution:=optional,
 org.eclipse.jdt.core;version=0;resolution:=optional,
 org.eclipse.jdt.core.dom;version=0;resolution:=optional,
 org.eclipse.jdt.core.dom.rewrite;version=0;resolution:=optional,
 org.eclipse.jdt.core.search;version=0;resolution:=optional,
 org.eclipse.jdt.internal.compiler.ast;version=0;resolution:=optional,
 org.eclipse.jdt.internal.compiler.lookup;version=0;resolution:=optional
 ,
 org.eclipse.jdt.internal.compiler.parser;version=0;resolution:=optional
 ,
 org.eclipse.jdt.internal.compiler.problem;version=0;resolution:=optiona
 l,
 org.eclipse.jdt.internal.core;version=0;resolution:=optional,
 org.eclipse.jdt.internal.core.dom.rewrite;version=0;resolution:=optiona
 l,
 org.eclipse.jdt.internal.corext.refactoring;version=0;resolution:=optio
 nal,
 org.eclipse.jdt.internal.corext.refactoring.structure;version=0;resolut
 ion:=optional,
 org.eclipse.jetty.jmx;version=0;resolution:=optional,
 org.ietf.jgss;version=0;resolution:=optional,
 org.joda.time;version=0;resolution:=optional,
 org.joda.time.format;version=0;resolution:=optional,
 org.mapstruct.ap.spi;version=0;resolution:=optional,
 org.mozilla.javascript;version=0;resolution:=optional,
 org.mozilla.javascript.tools;version=0;resolution:=optional,
 org.osgi.framework;version=0;resolution:=optional,
 org.osgi.framework.wiring;version=0;resolution:=optional,
 org.slf4j;version=0;resolution:=optional,
 org.slf4j.event;version=0;resolution:=optional,
 org.slf4j.helpers;version=0;resolution:=optional,
 org.slf4j.spi;version=0;resolution:=optional,
 org.springframework.beans.factory.annotation;version=0;resolution:=opti
 onal,
 org.springframework.context.annotation;version=0;resolution:=optional,
 org.springframework.core.env;version=0;resolution:=optional,
 org.springframework.data.repository.query;version=0;resolution:=optiona
 l,
 org.springframework.stereotype;version=0;resolution:=optional,
 org.w3c.dom;version=0;resolution:=optional,
 org.w3c.dom.bootstrap;version=0;resolution:=optional,
 org.w3c.dom.ls;version=0;resolution:=optional,
 org.w3c.dom.traversal;version=0;resolution:=optional,
 org.xml.sax;version=0;resolution:=optional,
 org.xml.sax.ext;version=0;resolution:=optional,
 org.xml.sax.helpers;version=0;resolution:=optional,
 sun.misc;version=0;resolution:=optional,
 sun.util.calendar;version=0;resolution:=optional
Require-Bundle: com.onresolve.jira.groovy.groovyrunner
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9.0))"
Spring-Context: *
Tool: Bnd-3.5.0.201709291849
```
